version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/admin_backend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" 