name: CI/CD Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r admin_backend/requirements.txt
      - name: Run tests
        run: |
          # pytest 或自定义测试命令
          echo "No test yet"
      - name: Build static files
        run: |
          # npm run build 或其它静态资源构建命令
          echo "No frontend build yet"
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # 示例：rsync 或 scp 部署到服务器
          echo "请根据实际情况补充部署命令" 